spring:
  datasource:
      url: jdbc:mysql://localhost:3306/pure_blog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: root
      password: cryhnh22.
      driver-class-name: com.mysql.cj.jdbc.Driver

      mybatis-plus:
        global-config:
          db-config:
            id-type: auto
            field-strategy: not_empty
            #驼峰下划线转换
            column-underline: true
            #逻辑删除配置
            logic-delete-value: 0
            logic-not-delete-value: 1
            db-type: mysql
          refresh: false
        configuration:
          map-underscore-to-camel-case: true
          cache-enabled: false


        druid:
          aop-patterns: com.github.fuckcpp.*  #springbean监控
          filters: stat,wall,slf4j  #所有开启的功能

          stat-view-servlet: #监控页配置
            enabled: true
            login-username: admin
            login-password: admin
            resetEnable: false


          web-stat-filter: #web监控
            enabled: true
            urlPattern: /*
            exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


          filter:
            stat: #sql监控
              slow-sql-millis: 1000
              logSlowSql: true
              enabled: true
            wall: #防火墙
              enabled: true
              config:
                drop-table-allow: false
  mvc:
    static-path-pattern: /static/**

  thymeleaf:
      cache: false
      prefix:  classpath:/templates/
      check-template-location: true
      suffix: .html
      encoding: utf-8
      mode: HTML
